### ISSUE TITLE
Getting unexpected behavior while accessing a datastore value without putting it.

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-csharp#104]
Getting an exception use of closed network connection.

**Steps to replicate**
[dataStoreIssue.zip](https://github.com/getgauge/gauge-csharp/files/763859/dataStoreIssue.zip)
* Run the specs of the given project and check scenario `sdfsdf`
```
Test Name:	sdfsdf
Test Outcome:	Failed
Result StandardOutput:	
Gauge.CSharp.Runner.SandboxBuilder Creating a Sandbox in: C:\GaugeProject9\GaugeProject9\bin\Debug\
Unable to start plugin html-report. Plugin html-report is not installed. To install, run `gauge --install html-report`.
# kusfdsf sdfsdfsdf
  ## sdfsdf
        Error Message: Connection closed [127.0.0.1:53408] cause: EOF
        Stacktrace: 
        
    Error Message: write tcp 127.0.0.1:53405->127.0.0.1:53408: use of closed network connection
    Stacktrace: 
    
  Error Message: write tcp 127.0.0.1:53405->127.0.0.1:53408: use of closed network connection
  Stacktrace: 
  

  Error Message: write tcp 127.0.0.1:53405->127.0.0.1:53408: use of closed network connection
  Stacktrace: 
  
Gauge.CSharp.Runner.GaugeListener System.ArgumentException: Sequence contained null element
Parameter name: values
   at Google.Protobuf.Collections.RepeatedField`1.AddRange(IEnumerable`1 values)
   at Gauge.CSharp.Runner.Processors.StepExecutionEndingProcessor.ExecuteHooks(Message request) in C:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\gauge-csharp\Runner\Processors\StepExecutionEndingProcessor.cs:line 33
   at Gauge.CSharp.Runner.Processors.HookExecutionProcessor.Process(Message request) in C:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\gauge-csharp\Runner\Processors\HookExecutionProcessor.cs:line 62
   at Gauge.CSharp.Runner.GaugeListener.PollForMessages() in C:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\gauge-csharp\Runner\GaugeListener.cs:line 49
Specifications:	1 executed	0 passed	1 failed	0 skipped
Scenarios:	1 executed	0 passed	1 failed	0 skipped

Total time taken: 64ms
```
**Version**
```
Gauge version: 0.8.0.nightly-2017-02-06

Plugins
-------
csharp (0.9.3.nightly-2017-01-30)
```

**Comment by BugDiver** [comment]
The issue is not related to `datastore`. The actual exception is happening in `GaugeMessage.WriteMessage`.

**Comment by BugDiver** [comment]
Fix should be available in nightly >=  13-02-2017
