### ISSUE TITLE
Using before hooks on the same method is giving exceptions

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-csharp#105]
Using before hooks on the same method is giving exceptions

```
        [BeforeSpec]
        [BeforeScenario]
        [BeforeStep]
        [BeforeSuite]
        public void BeforeScenario()
        {
            Console.Write("before\n\n\n");
            GaugeMessages.WriteMessage("before");
        }
```

```
Test Name:	Scenario Heading
Test Outcome:	Failed
Result StandardOutput:	
Gauge.CSharp.Runner.SandboxBuilder Creating a Sandbox in: C:\GaugeProject9\GaugeProject9\bin\Debug\
Unable to start plugin html-report. Plugin html-report is not installed. To install, run `gauge --install html-report`.
  Error Message: Connection closed [127.0.0.1:53754] cause: EOF
  Stacktrace: 
  
  Error Message: write tcp 127.0.0.1:53751->127.0.0.1:53754: use of closed network connection
  Stacktrace: 
  
Gauge.CSharp.Runner.GaugeListener System.Reflection.AmbiguousMatchException: Multiple custom attributes of the same type found.

Server stack trace: 
   at System.Attribute.GetCustomAttribute(MemberInfo element, Type attributeType, Boolean inherit)
   at Gauge.CSharp.Runner.Models.HookMethod..ctor(MethodInfo methodInfo, Assembly targetLibAssembly) in C:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\gauge-csharp\Runner\Models\HookMethod.cs:line 40
   at Gauge.CSharp.Runner.Models.HookRegistry.<AddHookOfType>b__20_0(MethodInfo info) in C:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\gauge-csharp\Runner\Models\HookRegistry.cs:line 102
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at Gauge.CSharp.Runner.Models.HookRegistry.AddHookOfType(String hookType, IEnumerable`1 hooks) in C:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\gauge-csharp\Runner\Models\HookRegistry.cs:line 102
   at Gauge.CSharp.Runner.Models.HookRegistry..ctor(IAssemblyLoader assemblyLoader) in C:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\gauge-csharp\Runner\Models\HookRegistry.cs:line 52
   at Gauge.CSharp.Runner.Sandbox.GetHooksFromRegistry(String hookType) in C:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\gauge-csharp\Runner\Sandbox.cs:line 275
   at Gauge.CSharp.Runner.Sandbox.ExecuteHooks(String hookType, IHooksStrategy strategy, IList`1 applicableTags) in C:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\gauge-csharp\Runner\Sandbox.cs:line 206
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Gauge.CSharp.Runner.ISandbox.ExecuteHooks(String hookType, IHooksStrategy strategy, IList`1 applicableTags)
   at Gauge.CSharp.Runner.MethodExecutor.ExecuteHooks(String hookType, HooksStrategy strategy, IList`1 applicableTags) in C:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\gauge-csharp\Runner\MethodExecutor.cs:line 75
   at Gauge.CSharp.Runner.Processors.HookExecutionProcessor.ExecuteHooks(Message request) in C:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\gauge-csharp\Runner\Processors\HookExecutionProcessor.cs:line 49
   at Gauge.CSharp.Runner.Processors.HookExecutionProcessor.Process(Message request) in C:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\gauge-csharp\Runner\Processors\HookExecutionProcessor.cs:line 62
   at Gauge.CSharp.Runner.Processors.ExecutionStartingProcessor.Process(Message request) in C:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\gauge-csharp\Runner\Processors\ExecutionStartingProcessor.cs:line 48
   at Gauge.CSharp.Runner.GaugeListener.PollForMessages() in C:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\gauge-csharp\Runner\GaugeListener.cs:line 49
Specifications:	0 executed	0 passed	0 failed	0 skipped
Scenarios:	0 executed	0 passed	0 failed	0 skipped

Total time taken: 39ms
```

**Version**
```
Gauge version: 0.8.0.nightly-2017-02-06

Plugins
-------
csharp (0.9.3.nightly-2017-01-30)
```

**Comment by sriv** [comment]
Fix should be in nightly >= 19/04/17
