### ISSUE TITLE
Gauge Error in Visual Studio

### ISSUE THREAD

**Issue by SreejithShenoi** [getgauge/gauge-csharp#112]
I am on Gauge version 0.9.2. Installed Gauge VS2013 extension and created a Gauge project.
On opening spec file from Visual Studio IDE, getting an error "Unable to Launch Gauge Daemon. Check ouput window for more detail".
Output Window logs from Gauge
[Debug] Opening Gauge Daemon for Project : GaugeProject1, at ports: 1000, 2000
[Debug] Opening Gauge Daemon with PID: 13284
[Error] Failed to start Gauge Daemon: System.Exception: Could not connect ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:1000
at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
at Gauge.CSharp.Core.TcpClientWrapper..ctor(Int32 port)
--- End of inner exception stack trace ---
at Gauge.CSharp.Core.TcpClientWrapper..ctor(Int32 port)
at Gauge.VisualStudio.Core.GaugeService.StartGaugeAsDaemon(Project gaugeProject)
Output window logs from Tests
------ Load Playlist started ------
========== Load Playlist finished (0:00:00.003) ==========
The given key was not present in the dictionary.
------ Discover test started ------
========== Discover test finished: 0 found (0:00:01.954) ==========

**Comment by nehashri** [comment]
Is this issue still occurring?

**Comment by SreejithShenoi** [comment]
@nehashri 
Yes I am facing this issue now as well.

**Comment by tzuravner** [comment]
I'm also encountering it randomly.
restarting the VS usually working until the next time it reappears.
