### ISSUE TITLE
The Carbon driver has not been ported to 64bits

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-csharp#113]
**Expected behavior**
Should be able to run Gauge csharp build using Mono

**Actual behavior**
Gauge-csharp build fails using Mono with the following exception
```
at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Windows.Forms.XplatUICarbon.CGDisplayBounds (intptr) [0x00002] in <37dfd86a0d3248c0b8cd4af52ec71426>:0
  at System.Windows.Forms.XplatUICarbon.get_WorkingArea () [0x00005] in <37dfd86a0d3248c0b8cd4af52ec71426>:0
  at System.Windows.Forms.XplatUICarbon.get_VirtualScreen () [0x00000] in <37dfd86a0d3248c0b8cd4af52ec71426>:0
  at System.Windows.Forms.XplatUI.get_VirtualScreen () [0x00000] in <37dfd86a0d3248c0b8cd4af52ec71426>:0
  at System.Windows.Forms.Screen..cctor () [0x00034] in <37dfd86a0d3248c0b8cd4af52ec71426>:0
  at (wrapper runtime-invoke) object.runtime_invoke_void (object,intptr,intptr,intptr) [0x0001e] in <c9f8153c41de4f8cbafd0e32f9bf6b28>:0
  at <unknown> <0xffffffff>
  at Gauge.CSharp.Lib.DefaultScreenGrabber.TakeScreenShot () [0x00000] in <c8035a62d93f4710b3213cfceeb3d8c2>:0
  at (wrapper runtime-invoke) <Module>.runtime_invoke_object__this__ (object,intptr,intptr,intptr) [0x0004e] in <c8035a62d93f4710b3213cfceeb3d8c2>:0
  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) [0x0000c] in <c9f8153c41de4f8cbafd0e32f9bf6b28>:0
  at System.Reflection.MonoMethod.Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo) [0x00032] in <c9f8153c41de4f8cbafd0e32f9bf6b28>:0
  at System.Reflection.MethodBase.Invoke (object,object[]) [0x00000] in <c9f8153c41de4f8cbafd0e32f9bf6b28>:0
  at Gauge.CSharp.Runner.Sandbox.TryScreenCapture (byte[]&) [0x00020] in <ff7b2f32481b4ef9b7d8aebd65072612>:0
  at (wrapper remoting-invoke-with-check) Gauge.CSharp.Runner.Sandbox.TryScreenCapture (byte[]&) [0x00032] in <ff7b2f32481b4ef9b7d8aebd65072612>:0
  at (wrapper xdomain-dispatch) Gauge.CSharp.Runner.Sandbox.TryScreenCapture (object,byte[]&,byte[]&,byte[]&) [0x00023] in <ff7b2f32481b4ef9b7d8aebd65072612>:0
  at (wrapper xdomain-invoke) Gauge.CSharp.Runner.Sandbox.TryScreenCapture (byte[]&) <0x001ba>
  at Gauge.CSharp.Runner.MethodExecutor.TakeScreenshot () <0x0002f>
  at Gauge.CSharp.Runner.MethodExecutor.Execute (Gauge.CSharp.Runner.Models.GaugeMethod,string[]) <0x0018e>
  at Gauge.CSharp.Runner.Processors.ExecuteStepProcessor.Process (Gauge.Messages.Message) <0x002f1>
  at Gauge.CSharp.Runner.GaugeListener.PollForMessages () <0x00160>
  at Gauge.CSharp.Runner.StartCommand.Execute () <0x00057>
  at Gauge.CSharp.Runner.Program.Main (string[]) <0x0009e>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void_object (object,intptr,intptr,intptr) <0x000d0>
Native stacktrace:
	0   mono                                0x000000010fe83061 mono_handle_native_crash + 257
	1   mono                                0x000000010fee8ec6 altstack_handle_and_restore + 70
	2   CoreGraphics                        0x00007fff950170bf CGDisplayBounds + 41
	3   ???                                 0x0000000114ace11e 0x0 + 4641841438
	4   ???                                 0x0000000114ac671f 0x0 + 4641810207
	5   mono                                0x000000010fdd9505 mono_jit_runtime_invoke + 2245
	6   mono                                0x000000010ffdad48 do_runtime_invoke + 88
	7   mono                                0x000000010ffd6cdd mono_runtime_class_init_full + 1021
	8   mono                                0x000000010fdd2efa mono_jit_compile_method_inner + 2442
	9   mono                                0x000000010fdd584a mono_jit_compile_method_with_opt + 714
	10  mono                                0x000000010fe8566f common_call_trampoline + 1199
	11  mono                                0x000000010fe85189 mono_magic_trampoline + 73
	12  ???                                 0x000000011046a39e 0x0 + 4568032158
	13  ???                                 0x0000000114ac60ea 0x0 + 4641808618
	14  ???                                 0x0000000114ac63f5 0x0 + 4641809397
	15  mono                                0x000000010fdd9505 mono_jit_runtime_invoke + 2245
	16  mono                                0x000000010ffdad48 do_runtime_invoke + 88
	17  mono                                0x000000010ffde82c mono_runtime_try_invoke_array + 1420
	18  mono                                0x000000010ff3ac6d ves_icall_InternalInvoke + 653
	19  ???                                 0x00000001143581e1 0x0 + 4634018273
	20  ???                                 0x0000000113dc66cb 0x0 + 4628178635
	21  ???                                 0x0000000114ac5ec6 0x0 + 4641808070
	22  ???                                 0x0000000113da95cb 0x0 + 4628059595
Debug info from gdb:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python/lldb/__init__.py", line 98, in <module>
    import six
ImportError: No module named six
(lldb) command source -s 0 '/tmp/mono-gdb-commands.tnXuQ7'
Executing commands in '/tmp/mono-gdb-commands.tnXuQ7'.
(lldb) process attach --pid 8355
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback ...
NameError: name 'run_one_line' is not defined
Process 8355 stopped
* thread #1: tid = 0x4abc, 0x00007fff86ac1582 libsystem_kernel.dylib`__wait4 + 10, name = 'tid_50f', queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame #0: 0x00007fff86ac1582 libsystem_kernel.dylib`__wait4 + 10
libsystem_kernel.dylib`__wait4:
->  0x7fff86ac1582 <+10>: jae    0x7fff86ac158c            ; <+20>
    0x7fff86ac1584 <+12>: movq   %rax, %rdi
    0x7fff86ac1587 <+15>: jmp    0x7fff86abb7f2            ; cerror
    0x7fff86ac158c <+20>: retq   
Executable module set to "/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono".
Architecture set to: x86_64-apple-macosx.
(lldb) thread list
Process 8355 stopped
* thread #1: tid = 0x4abc, 0x00007fff86ac1582 libsystem_kernel.dylib`__wait4 + 10, name = 'tid_50f', queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  thread #2: tid = 0x4abd, 0x00007fff86ac0db6 libsystem_kernel.dylib`__psynch_cvwait + 10, name = 
...
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
Process 8355 stopped
* thread #1: tid = 0x4abc, 0x00007fff86ac1582 libsystem_kernel.dylib`__wait4 + 10, name = 'tid_50f', queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00007fff86ac1582 libsystem_kernel.dylib`__wait4 + 10
libsystem_kernel.dylib`__wait4:
    0x7fff86ac1582 <+10>: jae    0x1758c                   ; <+20>
    0x7fff86ac1584 <+12>: movq   %rax, %rdi
    0x7fff86ac1587 <+15>: jmp    0x117f2                   ; cerror
    0x7fff86ac158c <+20>: retq   
Process 8355 detached
(lldb) quit
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'lldb' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'lldb' is not defined
./run.sh: line 3:  8355 Abort trap: 6           mono ./bin/Gauge.CSharp.Runner.exe $1
            Error Message: write tcp 127.0.0.1:52836->127.0.0.1:52902: use of closed network connection
            Stacktrace: 
            
            Failed Step: Option "Log in" should be available
            Specification: Specs/PlaceOrder.spec
            Error Message: Connection closed [127.0.0.1:52902] cause: EOF
            Stacktrace: 
            
    Error Message: write tcp 127.0.0.1:52836->127.0.0.1:52902: use of closed network connection
    Stacktrace: 
    
  ## Cart retains items until order is placed	Failed to initialize scenario datastore. Error: write tcp 127.0.0.1:52836->127.0.0.1:52902: use of closed network connection
    Error Message: write tcp 127.0.0.1:52836->127.0.0.1:52902: use of closed network connection
    Stacktrace: 
    
    Error Message: write tcp 127.0.0.1:52836->127.0.0.1:52902: use of closed network connection
    Stacktrace: 
```
**Steps to replicate**
* https://travis-ci.org/getgauge-examples/csharp-selenium

**Version**
```
Gauge 0.9.2
gauge-csharp 0.10.1
```

**Comment by pmfws** [comment]
I experience the same behavior trying to run Fiddler for OS X Beta on Mac OS 10.12.6 using Mono 5.7.0.370
