### ISSUE TITLE
MethodScanner Steps Fetch failed, Failed to connect to Gauge API

### ISSUE THREAD

**Issue by jacobbarsoe** [getgauge/gauge-csharp#122]
I don't know if this is a bug in gauge gauge-csharp or some critical software that are conflicting here. 

Perhaps some of you guys have seen a similar problem or can guide in what direction to debug my setup.

Thanks in advance.

Br,
Jacob

### Expected behavior
Test should execute steps

### Actual behavior

Done building project "Test.csproj".
snippet:
Server stack trace:
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Gauge.CSharp.Runner.Sandbox.GetStepMethods() in C:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\gauge-csharp\Runner\Sandbox.cs:line 125
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Gauge.CSharp.Runner.ISandbox.GetStepMethods()
   at Gauge.CSharp.Runner.MethodScanner.GetStepRegistry() in C:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\gauge-csharp\Runner\MethodScanner.cs:line
48

MethodScanner Steps Fetch failed, Failed to connect to Gauge API

### Steps to reproduce
run a test

### Gauge version
Gauge version: 0.9.4
Commit Hash: c96bdbb

Plugins
-------
csharp (0.10.1)
html-report (4.0.2)
java (0.6.5)
screenshot (0.0.1)
spectacle (0.1.2)

**Comment by nehashri** [comment]
@jacobbarsoe Looking at the stacktrace, it is hard to find out cause of the issue. If possible,  can you share a sample project to reproduce the above error?

**Comment by jacobbarsoe** [comment]
Thank you. This was exactly the input I needed. I recently added a new class that was overloading an otherclass, that's apparently not allowed. Is it stated somewhere that you are not allowed to do overloading?

**Comment by nehashri** [comment]
@jacobbarsoe can still share a sample project which causes this issue. It would help us handle such scenarios better.

**Comment by jacobbarsoe** [comment]
https://github.com/jacobbarsoe/gauge-test-bug

note stepimplementation2 overloads stepimplementation

**Comment by jacobbarsoe** [comment]
should I reopen the issue?

**Comment by sriv** [comment]
@jacobbarsoe - This definitely looks like something worth investigating. Thanks.

Reopening.

**Comment by ramya-KM** [comment]
![image](https://user-images.githubusercontent.com/39360628/40156513-46aab8e4-59dd-11e8-8813-28b641de7487.png)

I got the below error when i tried running the spec in guage

**Comment by sriv** [comment]
@ramya-KM - are you doing something similar to what @jacobbarsoe mentioned above? The errors may look similar, but could be because of different reasons.
