### ISSUE TITLE
Duplicate steps cause runner to crash

### ISSUE THREAD

**Issue by FathimaHarris** [getgauge/gauge-csharp#13]
When there are two methods with the same step text attribute, the Gauge CSharp runner crashes.

Stack trace:

```
Application: Gauge.Csharp.Runner.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
Stack:
   at System.ThrowHelper.ThrowArgumentException(System.ExceptionResource)
   at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Insert(System.__Canon, System.__Canon, Boolean)
   at System.Linq.Enumerable.ToDictionary[[System.Collections.Generic.KeyValuePair`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.Collections.Generic.KeyValuePair`2<System.__Canon,System.__Canon>>, System.Func`2<System.Collections.Generic.KeyValuePair`2<System.__Canon,System.__Canon>,System.__Canon>, System.Func`2<System.Collections.Generic.KeyValuePair`2<System.__Canon,System.__Canon>,System.__Canon>, System.Collections.Generic.IEqualityComparer`1<System.__Canon>)
   at Gauge.CSharp.Runner.StepRegistry..ctor(System.Collections.Generic.IEnumerable`1<System.Collections.Generic.KeyValuePair`2<System.String,System.Reflection.MethodInfo>>)
   at Gauge.CSharp.Runner.MethodScanner.GetStepRegistry()
   at Gauge.CSharp.Runner.MessageProcessorFactory.InitializeProcessors(Gauge.CSharp.Runner.IMethodScanner)
   at Gauge.CSharp.Runner.MessageProcessorFactory..ctor()
   at Gauge.CSharp.Runner.StartPhaseExecutor..ctor()
   at Gauge.CSharp.Runner.StartPhaseExecutor.GetDefaultInstance()
   at Gauge.CSharp.Runner.PhaseExecutorFactory.GetExecutor(System.String)
   at Gauge.CSharp.Runner.Program.Main(System.String[])

**Comment by sriv** [comment]
Fixed via 2c38fbc4b11ae01245b5c3bfb250ba718e120783
