### ISSUE TITLE
Should be able to capture screenshot

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-csharp#141]
Getting the following error
```
        Failed Step: Vowels in English language are "aeiou".
        Specification: specs\example.spec:11
        Error Message: The system cannot find the file specified
        Stacktrace:
           at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
           at Gauge.CSharp.Lib.DefaultScreenGrabber.TakeScreenShot()
           at Gauge.CSharp.Lib.GaugeScreenshots.Capture()
           at one.StepImplementation.SetLanguageVowels(String vowelString) in ...\one\StepImplementation.cs:line 17
```

**Steps to replicate**
* Create a `gauge-csharp` project
* Add GaugeScreenshots.Capture() to the step
```
        [Step("Vowels in English language are <vowelString>.")]
        public void SetLanguageVowels(string vowelString)
        {
            Gauge.CSharp.Lib.GaugeScreenshots.Capture();

            _vowels = new HashSet<char>();
            foreach (var c in vowelString)
            {
                _vowels.Add(c);
            }
        }
````

**Version**
```
Gauge version: 1.0.1.nightly-2018-07-18
Commit Hash: e62f840

Plugins
-------
csharp (0.10.5.nightly-2018-07-19)
html-report (4.0.5.nightly-2018-07-11)
```
Blocks #137

**Comment by sguptatw** [comment]
Works as expected when screenshot is installed.
