### ISSUE TITLE
problems in running the sample

### ISSUE THREAD

**Issue by alonye** [getgauge/gauge-csharp#148]
Hello, 
please help me solve the following issue when trying to run the sample:
### Expected behavior
This output(from get_started):
Specifications:	1 executed	1 passed	0 failed	0 skipped
  Scenarios:    	2 executed	2 passed	0 failed	0 skipped

  Total time taken: 80ms

### Actual behavior
C:\Users\alony\Downloads\GaugeTest>gauge run specs
Building project: C:/Users/alony/Downloads/GaugeTest/GaugeTest.csproj
  C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe  C:/Users/alony/Downloads/GaugeTest/GaugeTest.csproj /t:Build /m  /nodeReuse:False  /v:q  /p:RestorePackages="False" /p:OutputPath="C:\Users\alony\Downloads\GaugeTest\gauge_bin" /p:Platform="Any CPU" /p:Configuration="Debug" /logger:Fake.MsBuildLogger+ErrorLogger,"C:\Users\alony\AppData\Roaming\gauge\plugins\csharp\0.10.4\bin\FakeLib.dll"
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

  Error Message: Connection closed [127.0.0.1:51745] cause: EOF
  Stacktrace:

  Error Message: write tcp 127.0.0.1:51743->127.0.0.1:51745: use of closed network connection
  Stacktrace:

Gauge.CSharp.Runner.GaugeListener System.Runtime.Remoting.RemotingException: The argument type 'Gauge.CSharp.Lib.ExecutionContext' cannot be converted into parameter type 'Gauge.CSharp.Lib.ExecutionContext'. ---> System.InvalidCastException: Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Runtime.Remoting.Messaging.Message.CoerceArg(Object value, Type pt)
   --- End of inner exception stack trace ---

Server stack trace:
   at System.Runtime.Remoting.Messaging.Message.CoerceArg(Object value, Type pt)
   at System.Runtime.Remoting.Messaging.Message.CoerceArgs(MethodBase mb, Object[] args, ParameterInfo[] pi)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Gauge.CSharp.Runner.ISandbox.ExecuteHooks(String hookType, IHooksStrategy strategy, IList`1 applicableTags, ExecutionContext executionContext)
   at Gauge.CSharp.Runner.MethodExecutor.ExecuteHooks(String hookType, HooksStrategy strategy, IList`1 applicableTags, ExecutionContext executionContext) in C:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\Runner\MethodExecutor.cs:line 74
   at Gauge.CSharp.Runner.Processors.HookExecutionProcessor.ExecuteHooks(Message request) in C:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\Runner\Processors\HookExecutionProcessor.cs:line 64
   at Gauge.CSharp.Runner.Processors.HookExecutionProcessor.Process(Message request) in C:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\Runner\Processors\HookExecutionProcessor.cs:line 52
   at Gauge.CSharp.Runner.Processors.ExecutionStartingProcessor.Process(Message request) in C:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\Runner\Processors\ExecutionStartingProcessor.cs:line 45
   at Gauge.CSharp.Runner.GaugeListener.PollForMessages() in C:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\Runner\GaugeListener.cs:line 49
Successfully generated html-report to => C:\Users\alony\Downloads\GaugeTest\reports\html-report\index.html
Specifications: 0 executed      0 passed        0 failed        0 skipped
Scenarios:      0 executed      0 passed        0 failed        0 skipped

Total time taken: 51ms

### Steps to reproduce
1. I downloaded the zip file.
2. executed these commands:
2.1. Expand-Archive -Path gauge-1.0.0-windows.x86_64.zip -DestinationPath custom_path
2.2 gauge init csharp
2.3. gauge run specs

### Gauge version
```
Run gauge -v on your system and paste the results here.
Gauge version: 1.0.0
Commit Hash: 5a99965

Plugins
-------
csharp (0.10.4)
html-report (4.0.5)
screenshot (0.0.1)

**Comment by sriv** [comment]
Hi, you are probably seeing this because of #136 

This will be fixed in the upcoming release of Gauge-CSharp (0.10.5). In the meantime you can try using the latest [nightly version](https://bintray.com/gauge/gauge-csharp/Nightly/_latestVersion).

Steps to install a nightly:
- download the file from (https://bintray.com/gauge/gauge-csharp/Nightly/_latestVersion)
- `gauge install csharp -f <path to downloaded file>`

Alternatively, edit the `packages.config` of the sample, and downgrade the `Gauge.CSharp.Lib` version to `0.7.1`.

**Comment by nehashri** [comment]
@alonye [Gauge-CSharp (0.10.5)](https://github.com/getgauge/gauge-csharp/releases/tag/v0.10.5) has been released now. You can download the latest version and see if it fixes your issue. If you still facing the issue please reopen this issue
