### ISSUE TITLE
 Failed to initialize suite datastore. Error: Connection closed [127.0.0.1:62438] cause: EOF

### ISSUE THREAD

**Issue by manavghaigithub** [getgauge/gauge-csharp#156]
### Expected behavior
Gauge should run after incorporating System.Text.Encoding.CodePages

### Actual behavior
Gauge is not starting execution and throwing error message.

### Steps to reproduce
1. Create .Net Core project
2. Include EPPPlus.Core package from NuGet. Microsoft's System.Text.Encoding.CodePages is part of this package
3. Create any one step implementation
4. Run from command prompt using "gauge run specs"
5. Gauge throws below exception which looks like something in Gauge is conflicting with System.Text.Encoding.CodePages

  Failed to initialize suite datastore. Error: Connection closed [127.0.0.1:62438] cause: EOF
Gauge.Dotnet.GaugeListener System.IO.FileLoadException: Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(IntPtr ptrNativeAssemblyLoadContext, IntPtr ptrAssemblyArray, Int32 iAssemblyArrayLen, IntPtr ptrSymbols, Int32 iSymbolArrayLen, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
   at Gauge.Dotnet.Wrappers.AssemblyWrapper.LoadFrom(String location) in /Users/vagrant/go-agent-17.4.0/pipelines/dotnet-package/src/Wrappers/AssemblyWrapper.cs:line 42
   at Gauge.Dotnet.AssemblyLoader.ScanAndLoad(String path) in /Users/vagrant/go-agent-17.4.0/pipelines/dotnet-package/src/AssemblyLoader.cs:line 128
   at Gauge.Dotnet.AssemblyLoader..ctor(IAssemblyWrapper assemblyWrapper, IEnumerable`1 assemblyLocations, IReflectionWrapper reflectionWrapper) in /Users/vagrant/go-agent-17.4.0/pipelines/dotnet-package/src/AssemblyLoader.cs:line 43
   at Gauge.Dotnet.MessageProcessorFactory.GetProcessor(MessageType messageType, Boolean scan) in /Users/vagrant/go-agent-17.4.0/pipelines/dotnet-package/src/MessageProcessorFactory.cs:line 50
   at Gauge.Dotnet.GaugeListener.PollForMessages() in /Users/vagrant/go-agent-17.4.0/pipelines/dotnet-package/src/GaugeListener.cs:line 56
Successfully generated html-report to => C:\Users\mghai\Desktop\Gauge\Thamo\Framework\reports\html-report\index.html
Specifications: 0 executed      0 passed        0 failed        0 skipped
Scenarios:      0 executed      0 passed        0 failed        0 skipped

Total time taken: 876ms

### Gauge version
Gauge version: 1.0.2
Commit Hash: b4288bb

Plugins
-------
csharp (0.10.5)
dotnet (0.1.0)
html-report (4.0.6)
screenshot (0.0.1)

**Comment by NivedhaSenthil** [comment]
I tried adding `EPPPlus.Core` package and could run the sample project fine. Can you please share a project where we can reproduce this ?

**Comment by manavghaigithub** [comment]
Nivedha - Can you check the versions of Gauge i mentioned? Just want to ensure we are using same version.


________________________________

**Comment by manavghaigithub** [comment]
Nividha - I cannot share the project as i am at customer location but myself and another person in my team tried on two different machines and we got same problem. We actually created a brand new .net core project and included EPPPLus library but still ended up getting same problem.
