### ISSUE TITLE
getting io exception in gauge log file

### ISSUE THREAD

**Issue by Debashis9012** [getgauge/gauge-csharp#169]
### Expected behavior
there should not be any exception in log file

### Actual behavior
Kindly find the below error in the log file.
```
System.IO.IOException:  An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at Google.Protobuf.CodedInputStream.RefillBuffer(Boolean mustSucceed)
   at Google.Protobuf.CodedInputStream.ReadRawByte()
   at Google.Protobuf.CodedInputStream.SlowReadRawVarint32()
   at Google.Protobuf.CodedInputStream.ReadBytes()
   at Gauge.CSharp.Runner.GaugeListener.PollForMessages() in C:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\Runner\GaugeListener.cs:line 
```

### Steps to reproduce
Pre-requisite:
Install gauge nightly version and csharp release version

1. create csharp project
2. open it in visual studio
3. run tests
4. verify gauge.log file

### Gauge version
```
Gauge version: 1.0.6.nightly-2019-07-19
Commit Hash: c215a9f

Plugins
-------
csharp (0.10.5)
```

**Comment by BugDiver** [comment]
This plugin is not supported anymore. Please look at the README for deprecation notice.
