### ISSUE TITLE
not able to run test cases from command prompt

### ISSUE THREAD

**Issue by uzmar** [getgauge/gauge-csharp#34]
gets runner error when installed latest csharp plugin and tried to run test cases from cmd but it works fine from IDE.
 See logs:
<img width="551" alt="screen shot 2015-09-08 at 3 30 49 pm" src="https://cloud.githubusercontent.com/assets/10433272/9732090/abc1743e-563e-11e5-9188-0400f2a8ff51.png">

<img width="1034" alt="screen shot 2015-09-08 at 3 27 16 pm" src="https://cloud.githubusercontent.com/assets/10433272/9732063/7b0129a2-563e-11e5-958c-8894f3612b2c.png">

Logs from console
C:\Users\uzma\Documents\Project\gauge-example-csharp-master>gauge specs/
17:11:45.180 [WARN] C:\Users\uzma\Documents\Project\gauge-example-csharp-master\
specs\products.spec : line no: 9, Table not associated with a step, ignoring tab
le
Building Project: C:\Users\uzma\Documents\Project\gauge-example-csharp-master\Ga
uge.Example.sln
Success
[WARN] Steps Fetch failed, Failed to connect to Gauge API
Could not load file or assembly 'Gauge.CSharp.Lib, Version=0.4.3.0, Culture=neut
ral, PublicKeyToken=null' or one of its dependencies. The located assembly's man
ifest definition does not match the assembly reference. (Exception from HRESULT:
 0x80131040)

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembl
y 'Gauge.CSharp.Lib, Version=0.4.3.0, Culture=neutral, PublicKeyToken=null' or o
ne of its dependencies. The located assembly's manifest definition does not matc
h the assembly reference. (Exception from HRESULT: 0x80131040)

Server stack trace:
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, Int
Ptr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInst
Count, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32
typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] met
hodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] ge
nericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttrib
uteRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, Runtime
Module decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilte
rType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes,
RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters
, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decora
tedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFi
lterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecorate
dTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeMethodInfo me
thod, RuntimeType caType, Boolean inherit)
   at System.Reflection.RuntimeMethodInfo.GetCustomAttributes(Type attributeType
, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolea
n inherit)
   at Gauge.CSharp.Runner.Sandbox.<>c__DisplayClassa.<GetMethodsFromAssembly>b__
8(MethodInfo info) in c:\Program Files (x86)\Go Agent\pipelines\Gauge-Csharp\Run
ner\Sandbox.cs:line 129
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Gauge.CSharp.Runner.Sandbox.GetMethodsFromAssembly(Type type, Assembly ass
embly) in c:\Program Files (x86)\Go Agent\pipelines\Gauge-Csharp\Runner\Sandbox.
cs:line 127
   at Gauge.CSharp.Runner.Sandbox.<>c__DisplayClass4.<GetAllMethodsForSpecAssemb
lies>b__3(Assembly assembly) in c:\Program Files (x86)\Go Agent\pipelines\Gauge-
Csharp\Runner\Sandbox.cs:line 121
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Gauge.CSharp.Runner.Sandbox.GetAllMethodsForSpecAssemblies(String type) in
 c:\Program Files (x86)\Go Agent\pipelines\Gauge-Csharp\Runner\Sandbox.cs:line 0

   at Gauge.CSharp.Runner.Sandbox.GetHookRegistry() in c:\Program Files (x86)\Go
 Agent\pipelines\Gauge-Csharp\Runner\Sandbox.cs:line 55
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(
IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMes
sage msg)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage req
Msg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgDa
ta, Int32 type)
   at Gauge.CSharp.Runner.ISandbox.GetHookRegistry()
   at Gauge.CSharp.Runner.MethodScanner.GetHookRegistry() in c:\Program Files (x
86)\Go Agent\pipelines\Gauge-Csharp\Runner\MethodScanner.cs:line 84
   at Gauge.CSharp.Runner.MessageProcessorFactory.InitializeProcessors(IMethodSc
anner stepScanner) in c:\Program Files (x86)\Go Agent\pipelines\Gauge-Csharp\Run
ner\MessageProcessorFactory.cs:line 84
   at Gauge.CSharp.Runner.MessageProcessorFactory..ctor(ISandbox sandbox) in c:\
Program Files (x86)\Go Agent\pipelines\Gauge-Csharp\Runner\MessageProcessorFacto
ry.cs:line 37
   at Gauge.CSharp.Runner.StartPhaseExecutor..ctor() in c:\Program Files (x86)\G
o Agent\pipelines\Gauge-Csharp\Runner\StartPhaseExecutor.cs:line 60
   at Gauge.CSharp.Runner.StartPhaseExecutor.GetDefaultInstance() in c:\Program
Files (x86)\Go Agent\pipelines\Gauge-Csharp\Runner\StartPhaseExecutor.cs:line 41

   at Gauge.CSharp.Runner.PhaseExecutorFactory.GetExecutor(String phase) in c:\P
rogram Files (x86)\Go Agent\pipelines\Gauge-Csharp\Runner\PhaseExecutorFactory.c
s:line 27
   at Gauge.CSharp.Runner.Program.Main(String[] args) in c:\Program Files (x86)\
Go Agent\pipelines\Gauge-Csharp\Runner\Program.cs:line 49
17:12:10.188 [CRIT] Failed to start gauge API. Timed out connecting to [::]:2287
4

C:\Users\uzma\Documents\Project\gauge-example-csharp-master>

**Comment by sriv** [comment]
We've released 0.6.0 version of Gauge C# - it is still not available on the Gauge Repository, so you will have to do an offline install.

Can you please try these steps:
- Download Gauge CSharp v0.6.0 from [here](https://github.com/getgauge/gauge-csharp/releases/download/v0.6.0/gauge-csharp-0.6.0.zip)
- Run `gauge --install csharp -f gauge-csharp-0.6.0.zip` from the location where you saved the above file.
- Now retry your scenario.

Please let us know if this fixes the issue.

**Comment by uzmar** [comment]
I am still facing same issue, tried it with latest components 
Gauge Version: 0.1.8
CSharp plugin: 0.6.0
Visual Studio plugin: 0.1.0 (taken from GO pipeline).
Let me know if any other setup is required.

**Comment by sriv** [comment]
What is the version of `Gauge.Csharp.Lib` in the project? Can you try updating it to `0.5.2` and see if this error occurs?

**Comment by uzmar** [comment]
tried with that as well but same faced same issue. but it worked  when  deleted few folders (bin,obj, gauge-bin ) from solution and rebuild it as you suggested.
Thanks Srikanth.

**Comment by sriv** [comment]
The problem here was lack of signing `Gauge.CSharp.Lib` using a `snk`. This is now available for the last few versions (>=0.5.0). Closing this for now.
