### ISSUE TITLE
Running tests in VS 2015 fails

### ISSUE THREAD

**Issue by hakito** [getgauge/gauge-csharp#52]
Installed gauge 0.3.2
Gauge plugin for VS 0.2.1

When running tests in VS 2015 I get the following exception:

```
Test Name:	Vowel counts in multiple word
Test FullName:	[Specification Heading].[Vowel counts in multiple word]
Test Source:	a:\ExtDev\GaugeEvaluation\specs\example.spec : line 1
Test Outcome:	Failed
Test Duration:	0:00:00

Result Message:	
Object reference not set to an instance of an object.
   at Gauge.VisualStudio.TestAdapter.GaugeRunner.BuildOutputPath(String projectRoot)
   at Gauge.VisualStudio.TestAdapter.GaugeRunner.Run(TestCase testCase, Boolean isBeingDebugged, IFrameworkHandle frameworkHandle)
```

Tests run in VS 2013. But with version 0.2.0. (VS 2013 finds no update to 0.2.1)

**Comment by hakito** [comment]
Wrong repo
