### ISSUE TITLE
Make Gauge Daemon stop running for every project within solution

### ISSUE THREAD

**Issue by bkim54** [getgauge/gauge-csharp#97]
### Expected behavior

I have an existing VS solution where I have several projects, I added a Gauge test project to this solution to do some Testing. I Expect gauge to only run for the gauge project
### Actual behavior

Every time I open the solution in VS, the gauge daemon tries to open in every project. Here is the stack trace
`[Debug] Opening Gauge Daemon with PID: 5204
[Error] Failed to start Gauge Daemon: System.Exception: Could not connect ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:1000
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at Gauge.CSharp.Core.TcpClientWrapper..ctor(Int32 port)
   --- End of inner exception stack trace ---
   at Gauge.CSharp.Core.TcpClientWrapper..ctor(Int32 port)
   at Gauge.VisualStudio.Core.Helpers.GaugeDaemonHelper.StartGaugeAsDaemon(Project gaugeProject)`
### Steps to reproduce
1. Have an existing VS solution file
2. Add a gauge project to the solution
3. close and reopen the solution
### Gauge version

Gauge version: 0.6.2

Plugins

csharp (0.9.2)
html-report (2.1.1)
xml-report (0.1.3)

**Comment by sriv** [comment]
This issue was moved to getgauge/gauge-visualstudio#183
