### ISSUE TITLE
Exception running tests from existing c# solution with an existing gauge web project added

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-csharp#99]
**Expected behavior**
Should be able to run the specs without an exception

**Actual behavior**
Getting an exception
```
Test Name:	Get Started
Test Outcome:	Failed
Result StandardOutput:	
Gauge.CSharp.Runner.SandboxBuilder Creating a Sandbox in: Z:\Documents\Visual Studio 2015\Projects\GaugeWebdriverProject1\GaugeWebdriverProject1\bin\Debug\
Unable to connect to plugin Html Report 2.2.0. proto: required field "SuiteExecutionResult.SuiteResult.PreHookFailure.StackTrace" not set

  Error Message: Connection closed [127.0.0.1:50171] cause: EOF
  Stacktrace: 
  
  Error Message: write tcp 127.0.0.1:50169->127.0.0.1:50171: use of closed network connection
  Stacktrace: 
  
Gauge.CSharp.Runner.GaugeListener System.NullReferenceException: Object reference not set to an instance of an object.
   at Google.ProtocolBuffers.ByteString.CopyFrom(Byte[] bytes)
   at Gauge.CSharp.Runner.MethodExecutor.TakeScreenshot() in c:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\gauge-csharp\Runner\MethodExecutor.cs:line 102
   at Gauge.CSharp.Runner.MethodExecutor.ExecuteHooks(String hookType, HooksStrategy strategy, IList`1 applicableTags) in c:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\gauge-csharp\Runner\MethodExecutor.cs:line 77
   at Gauge.CSharp.Runner.Processors.HookExecutionProcessor.ExecuteHooks(Message request) in c:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\gauge-csharp\Runner\Processors\HookExecutionProcessor.cs:line 49
   at Gauge.CSharp.Runner.Processors.HookExecutionProcessor.Process(Message request) in c:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\gauge-csharp\Runner\Processors\HookExecutionProcessor.cs:line 62
   at Gauge.CSharp.Runner.Processors.ExecutionStartingProcessor.Process(Message request) in c:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\gauge-csharp\Runner\Processors\ExecutionStartingProcessor.cs:line 48
   at Gauge.CSharp.Runner.GaugeListener.PollForMessages() in c:\Program Files (x86)\Go Agent\pipelines\Csharp-Package\gauge-csharp\Runner\GaugeListener.cs:line 52
Specifications:	0 executed	0 passed	0 failed	0 skipped
Scenarios:	0 executed	0 passed	0 failed	0 skipped

Total time taken: 141ms
```
**Version**
```
Gauge version: 0.6.3.nightly-2016-12-07

Plugins
-------
csharp (0.9.3.nightly-2016-12-09)
html-report (2.2.0.nightly-2016-12-06)
java (0.5.1.nightly-2016-08-18)
ruby (0.3.2.nightly-2016-08-22)
xml-report (0.1.4.nightly-2016-07-25)
```

**Comment by sriv** [comment]
@sguptatw - is this still an issue? If persists, could you please upload a sample project that can be used to reproduce this?
